name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker environment
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub (optional, if pushing image)
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Create .env file
        run: |
          cat <<EOF > .env
          GEMINI_API_KEY=PLACEHOLDER_API_KEY
          # Firebase Configuration
          VITE_FIREBASE_API_KEY=AIzaSyAafrcgrIDJ_rlhzmrPR5ltJPkOOpnzuQ8
          VITE_FIREBASE_AUTH_DOMAIN=wise-news-2a915.firebaseapp.com
          VITE_FIREBASE_PROJECT_ID=wise-news-2a915
          VITE_FIREBASE_STORAGE_BUCKET=wise-news-2a915.firebasestorage.app
          VITE_FIREBASE_MESSAGING_SENDER_ID=26946717632
          VITE_FIREBASE_APP_ID=1:26946717632:web:a8a8cc7674319b8c7b2a25
          VITE_FIREBASE_MEASUREMENT_ID=G-02WKRR3R4G
          VITE_API_BASE_URL=https://photo-api.gitlabserver.id.vn
          EOF


      - name: install package
        run: yarn

      - name: Build Docker image
        run: docker build -t ${{ secrets.IMAGE_NAME }}-production:${{ secrets.TAG_NAME }} .

      - name: Add tag docker image (optional)
        run: docker tag ${{ secrets.IMAGE_NAME }}-production:${{ secrets.TAG_NAME }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}-production:${{ secrets.TAG_NAME }}_${{ github.sha }}

      - name: Push Docker image to docker hub (optional)
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}-production:${{ secrets.TAG_NAME }}_${{ github.sha }}

      - name: Copy nginx config & script to server
        env:
          SSH_PASS: ${{ secrets.SSH_PASS }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          sshpass -p $SSH_PASS scp -o StrictHostKeyChecking=no -P 24700 ./snap-photo.conf ./config.sh $SSH_USERNAME@$SSH_HOST:/container/
      
      - name: Deploy to Server (using SSH and Docker)
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_PASS: ${{ secrets.SSH_PASS }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          TAG_NAME: ${{ secrets.TAG_NAME }}
        run: |
          sshpass -p $SSH_PASS ssh -o StrictHostKeyChecking=no -p 24700 $SSH_USERNAME@$SSH_HOST << 'EOF'
            mkdir -p /container && cd /container
            if docker ps -aq --filter name=${{ secrets.IMAGE_NAME }}-production | grep -q .; then
                docker stop ${{ secrets.IMAGE_NAME }}-production || true
                docker rm -f ${{ secrets.IMAGE_NAME }}-production || true
            fi
            if docker images --filter=reference=${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}-production --quiet | grep -q .; then
                docker images --filter=reference=${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}-production --quiet | xargs -r docker rmi -f
            fi
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}-production:${{ secrets.TAG_NAME }}_${{ github.sha }}
            docker run -d -p 3098:3000 --name ${{ secrets.IMAGE_NAME }}-production --restart always  ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}-production:${{ secrets.TAG_NAME }}_${{ github.sha }}
          EOF
      - name: Run custom config script on server
        env:
          SSH_PASS: ${{ secrets.SSH_PASS }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          sshpass -p $SSH_PASS ssh -o StrictHostKeyChecking=no -p 24700 $SSH_USERNAME@$SSH_HOST "cd /container && chmod +x config.sh && ./config.sh"
